export const SCHOOL_STATES: Record<string, string> = {
    // Exact mapping for 100% accuracy based on school names in the database
    "Frederick P. Whiddon College of Medicine at the University of South Alabama": "AL",
    "University of Alabama at Birmingham Marnix E. Heersink School of Medicine": "AL",
    "Alice L. Walton School of Medicine": "AR",
    "University of Arkansas for Medical Sciences College of Medicine": "AR",
    "Arizona State University School of Medicine and Advanced Medical Engineering (SOMME)": "AZ",
    "University of Arizona College of Medicine - Phoenix": "AZ",
    "University of Arizona College of Medicine - Tucson": "AZ",
    "California University of Science and Medicine": "CA",
    "Charles R. Drew University of Medicine and Science College of Medicine": "CA",
    "Kaiser Permanente Bernard J. Tyson School of Medicine": "CA",
    "Keck School of Medicine of the University of Southern California": "CA",
    "Loma Linda University School of Medicine": "CA",
    "Stanford University School of Medicine": "CA",
    "UC Davis School of Medicine": "CA",
    "UC Riverside School of Medicine": "CA",
    "University of California, Davis, School of Medicine": "CA",
    "University of California, Irvine, School of Medicine": "CA",
    "University of California, Los Angeles David Geffen School of Medicine": "CA",
    "University of California, Riverside School of Medicine": "CA",
    "University of California, San Diego School of Medicine": "CA",
    "University of California, San Francisco, School of Medicine": "CA",
    "University of Colorado School of Medicine": "CO",
    "Frank H. Netter MD School of Medicine at Quinnipiac University": "CT",
    "University of Connecticut School of Medicine": "CT",
    "Yale School of Medicine": "CT",
    "George Washington University School of Medicine & Health Sciences": "DC",
    "Georgetown University School of Medicine": "DC",
    "Howard University College of Medicine": "DC",
    "Charles E. Schmidt College of Medicine at Florida Atlantic University": "FL",
    "Florida International University Herbert Wertheim College of Medicine": "FL",
    "Florida State University College of Medicine": "FL",
    "Nova Southeastern University Dr. Kiran C. Patel College of Allopathic Medicine": "FL",
    "University of Central Florida College of Medicine": "FL",
    "University of Florida College of Medicine": "FL",
    "University of Miami Leonard M. Miller School of Medicine": "FL",
    "USF Health Morsani College of Medicine": "FL",
    "Emory University School of Medicine": "GA",
    "Medical College of Georgia at Augusta University": "GA",
    "Mercer University School of Medicine": "GA",
    "Morehouse School of Medicine": "GA",
    "University of Hawaii, John A. Burns School of Medicine": "HI",
    "University of Iowa Roy J. and Lucille A. Carver College of Medicine": "IA",
    "Carle Illinois College of Medicine": "IL",
    "Chicago Medical School at Rosalind Franklin University of Medicine & Science": "IL",
    "Loyola University Chicago Stritch School of Medicine": "IL",
    "Northwestern University The Feinberg School of Medicine": "IL",
    "Rush Medical College of Rush University Medical Center": "IL",
    "Southern Illinois University School of Medicine": "IL",
    "University of Chicago Division of the Biological Sciences The Pritzker School of Medicine": "IL",
    "University of Illinois College of Medicine": "IL",
    "Indiana University School of Medicine": "IN",
    "University of Kansas School of Medicine": "KS",
    "University of Louisville School of Medicine": "KY",
    "Louisiana State University School of Medicine in New Orleans": "LA",
    "Louisiana State University School of Medicine in Shreveport": "LA",
    "Tulane University School of Medicine": "LA",
    "Boston University Aram V. Chobanian & Edward Avedisian School of Medicine": "MA",
    "Harvard Medical School": "MA",
    "Tufts University School of Medicine": "MA",
    "University of Massachusetts T.H. Chan School of Medicine": "MA",
    "Johns Hopkins University School of Medicine": "MD",
    "Uniformed Services University of the Health Sciences F. Edward Hebert School of Medicine": "MD",
    "University of Maryland School of Medicine": "MD",
    "Central Michigan University College of Medicine": "MI",
    "Michigan State University College of Human Medicine": "MI",
    "Oakland University William Beaumont School of Medicine": "MI",
    "University of Michigan Medical School": "MI",
    "Wayne State University School of Medicine": "MI",
    "Western Michigan University Homer Stryker M.D. School of Medicine": "MI",
    "Mayo Clinic Alix School of Medicine": "MN",
    "University of Minnesota Medical School": "MN",
    "Saint Louis University School of Medicine": "MO",
    "University of Missouri-Columbia School of Medicine": "MO",
    "University of Missouri-Kansas City School of Medicine": "MO",
    "Washington University in St. Louis School of Medicine": "MO",
    "University of Mississippi School of Medicine": "MS",
    "Brody School of Medicine at East Carolina University": "NC",
    "Duke University School of Medicine": "NC",
    "Methodist University Cape Fear Valley Health School of Medicine": "NC",
    "University of North Carolina at Chapel Hill School of Medicine": "NC",
    "Wake Forest University School of Medicine": "NC",
    "University of North Dakota School of Medicine and Health Sciences": "ND",
    "Creighton University School of Medicine": "NE",
    "University of Nebraska College of Medicine": "NE",
    "Geisel School of Medicine at Dartmouth": "NH",
    "Cooper Medical School of Rowan University": "NJ",
    "Hackensack Meridian School of Medicine": "NJ",
    "Rutgers New Jersey Medical School": "NJ",
    "Rutgers, Robert Wood Johnson Medical School": "NJ",
    "University of New Mexico School of Medicine": "NM",
    "Kirk Kerkorian School of Medicine at UNLV": "NV",
    "Roseman University College of Medicine": "NV",
    "University of Nevada, Reno School of Medicine": "NV",
    "Albany Medical College": "NY",
    "Albert Einstein College of Medicine": "NY",
    "Columbia University Vagelos College of Physicians and Surgeons": "NY",
    "CUNY School of Medicine": "NY",
    "Donald and Barbara Zucker School of Medicine at Hofstra/Northwell": "NY",
    "Icahn School of Medicine at Mount Sinai": "NY",
    "Jacobs School of Medicine and Biomedical Sciences at the University at Buffalo": "NY",
    "New York Medical College": "NY",
    "NYU Grossman Long Island School of Medicine": "NY",
    "NYU Grossman School of Medicine": "NY",
    "Renaissance School of Medicine at Stony Brook University": "NY",
    "State University of New York Upstate Medical University Alan and Marlene Norton College of Medicine": "NY",
    "SUNY Downstate Health Sciences University College of Medicine": "NY",
    "University of Rochester School of Medicine and Dentistry": "NY",
    "Weill Cornell Medicine": "NY",
    "Case Western Reserve University School of Medicine": "OH",
    "Northeast Ohio Medical University": "OH",
    "Ohio State University College of Medicine": "OH",
    "The University of Toledo College of Medicine and Life Sciences": "OH",
    "University of Cincinnati College of Medicine": "OH",
    "Wright State University Boonshoft School of Medicine": "OH",
    "University of Oklahoma College of Medicine": "OK",
    "Oregon Health & Science University School of Medicine": "OR",
    "Drexel University College of Medicine": "PA",
    "Geisinger Commonwealth School of Medicine": "PA",
    "Lewis Katz School of Medicine at Temple University": "PA",
    "Pennsylvania State University College of Medicine": "PA",
    "Perelman School of Medicine at the University of Pennsylvania": "PA",
    "Sidney Kimmel Medical College at Thomas Jefferson University": "PA",
    "University of Pittsburgh School of Medicine": "PA",
    "Ponce Health Sciences University School of Medicine": "PR",
    "San Juan Bautista School of Medicine": "PR",
    "Universidad Central del Caribe School of Medicine": "PR",
    "University of Puerto Rico School of Medicine": "PR",
    "The Warren Alpert Medical School of Brown University": "RI",
    "Medical University of South Carolina College of Medicine": "SC",
    "University of South Carolina School of Medicine Columbia": "SC",
    "University of South Carolina School of Medicine Greenville": "SC",
    "University of South Dakota, Sanford School of Medicine": "SD",
    "East Tennessee State University James H. Quillen College of Medicine": "TN",
    "Meharry Medical College": "TN",
    "Thomas F. Frist, Jr. College of Medicine at Belmont University": "TN",
    "University of Tennessee Health Science Center College of Medicine": "TN",
    "Vanderbilt University School of Medicine": "TN",
    "Anne Burnett Marion School of Medicine at TCU": "TX",
    "Baylor College of Medicine": "TX",
    "McGovern Medical School at the University of Texas Health Science Center at Houston": "TX",
    "Texas A&M University School of Medicine": "TX",
    "Texas A&M School of Medicine": "TX",
    "Texas Tech University Health Sciences Center Paul L. Foster School of Medicine": "TX",
    "Texas Tech University Health Sciences Center School of Medicine": "TX",
    "The University of Texas at Tyler School of Medicine": "TX",
    "The University of Texas Health Science Center at San Antonio Joe R. and Teresa Lozano Long School of Medicine": "TX",
    "University of Houston Tilman J. Fertitta Family College of Medicine": "TX",
    "University of Texas at Austin Dell Medical School": "TX",
    "University of Texas Medical Branch John Sealy School of Medicine": "TX",
    "University of Texas Rio Grande Valley School of Medicine": "TX",
    "University of Texas Southwestern Medical School": "TX",
    "Spencer Fox Eccles School of Medicine at the University of Utah": "UT",
    "Eastern Virginia Medical School": "VA",
    "University of Virginia School of Medicine": "VA",
    "Virginia Commonwealth University School of Medicine": "VA",
    "Virginia Tech Carilion School of Medicine": "VA",
    "Robert Larner, M.D., College of Medicine at the University of Vermont": "VT",
    "University of Washington School of Medicine": "WA",
    "Washington State University Elson S. Floyd College of Medicine": "WA",
    "Medical College of Wisconsin": "WI",
    "University of Wisconsin School of Medicine and Public Health": "WI",
    "Marshall University Joan C. Edwards School of Medicine": "WV",
    "West Virginia University School of Medicine": "WV",
    "University of British Columbia Faculty of Medicine": "BC",
    "Max Rady College of Medicine, Rady Faculty of Health Sciences, University of Manitoba": "MB",
    "Memorial University of Newfoundland Faculty of Medicine": "NL",
    "Dalhousie University Faculty of Medicine": "NS",
    "McMaster University Michael G. DeGroote School of Medicine": "ON",
    "Northern Ontario School of Medicine": "ON",
    "Queen's University Faculty of Health Sciences": "ON",
    "The University of Western Ontario - Schulich School of Medicine & Dentistry": "ON",
    "Toronto Metropolitan University School of Medicine": "ON",
    "University of Ottawa Faculty of Medicine": "ON",
    "Universite de Montreal Faculty of Medicine": "QC",
    "Universite de Sherbrooke Faculty of Medicine": "QC",
    "University of Saskatchewan College of Medicine": "SK"
};

export function getSchoolState(schoolName: string): string {
    return SCHOOL_STATES[schoolName] || "Unknown";
}

export const US_STATES = [
    "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "FL", "GA", "HI", "IA", "IL", "IN", 
    "KS", "KY", "LA", "MA", "MD", "MI", "MN", "MO", "MS", "NC", "ND", "NE", "NH", 
    "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "PR", "RI", "SC", "SD", "TN", 
    "TX", "UT", "VA", "VT", "WA", "WI", "WV"
];

export const CA_PROVINCES = ["BC", "MB", "NL", "NS", "ON", "QC", "SK"];
