-- Create activities table
CREATE TABLE IF NOT EXISTS public.activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    title TEXT,
    organization TEXT,
    city TEXT,
    country TEXT,
    experience_type TEXT,
    
    -- Using JSONB to store the array of date ranges
    date_ranges JSONB DEFAULT '[]'::jsonb,
    
    contact_name TEXT,
    contact_title TEXT,
    contact_email TEXT,
    contact_phone TEXT,
    
    status TEXT DEFAULT 'Draft',
    is_most_meaningful BOOLEAN DEFAULT FALSE,
    description TEXT,
    
    mme_action TEXT,
    mme_result TEXT,
    mme_essay TEXT,
    
    -- Using text array for competencies
    competencies TEXT[] DEFAULT '{}',
    
    due_date DATE
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;

-- Create Policy: Users can see only their own activities
CREATE POLICY "Users can view own activities" 
ON public.activities 
FOR SELECT 
USING (auth.uid() = user_id);

-- Create Policy: Users can insert their own activities
CREATE POLICY "Users can insert own activities" 
ON public.activities 
FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- Create Policy: Users can update their own activities
CREATE POLICY "Users can update own activities" 
ON public.activities 
FOR UPDATE 
USING (auth.uid() = user_id);

-- Create Policy: Users can delete their own activities
CREATE POLICY "Users can delete own activities" 
ON public.activities 
FOR DELETE 
USING (auth.uid() = user_id);

-- Automatically update 'updated_at' on row update
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_activities_updated_at
BEFORE UPDATE ON public.activities
FOR EACH ROW
EXECUTE PROCEDURE update_updated_at_column();
