-- Where the applicant is from, and where else they have ties.
--
-- profiles.legal_residence_state   the state AMCAS will list as legal residence. It is
--                                  what makes a public school's in-state seats apply.
-- profiles.residency_status        optional. Only ever used to say whether a school's
--                                  published policy excludes the applicant; the UI says so.
-- applicant_ties                   other states the applicant has a real connection to
--                                  (grew up, undergrad, family, work). Several per type is
--                                  normal, which is why this is a table, not columns.
-- activities.state                 W&A entries already carry city and country. A tie only
--                                  helps if the application shows it, and this is where
--                                  the application shows it.
--
-- Additive. applicant_ties cascades on user delete, like profiles and (since
-- 20260826020000) activities, so account deletion keeps working.
--
-- Idempotent: safe to re-run.

ALTER TABLE public.profiles
    ADD COLUMN IF NOT EXISTS legal_residence_state TEXT,
    ADD COLUMN IF NOT EXISTS residency_status TEXT;

ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_legal_residence_state_format;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_legal_residence_state_format
    CHECK (legal_residence_state IS NULL OR legal_residence_state ~ '^[A-Z]{2}$');

ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_residency_status_values;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_residency_status_values
    CHECK (residency_status IS NULL OR residency_status IN ('us_citizen_or_pr', 'daca', 'international'));

CREATE TABLE IF NOT EXISTS public.applicant_ties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    state TEXT NOT NULL CHECK (state ~ '^[A-Z]{2}$'),
    tie_type TEXT NOT NULL CHECK (tie_type IN ('grew_up', 'undergrad', 'family', 'work', 'other')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE (user_id, state, tie_type)
);

CREATE INDEX IF NOT EXISTS applicant_ties_user_id_idx ON public.applicant_ties (user_id);

ALTER TABLE public.applicant_ties ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own ties" ON public.applicant_ties;
CREATE POLICY "Users can view own ties"
ON public.applicant_ties FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own ties" ON public.applicant_ties;
CREATE POLICY "Users can insert own ties"
ON public.applicant_ties FOR INSERT
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own ties" ON public.applicant_ties;
CREATE POLICY "Users can update own ties"
ON public.applicant_ties FOR UPDATE
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own ties" ON public.applicant_ties;
CREATE POLICY "Users can delete own ties"
ON public.applicant_ties FOR DELETE
USING (auth.uid() = user_id);

ALTER TABLE public.activities
    ADD COLUMN IF NOT EXISTS state TEXT;
